# Generated by Django 5.2.8 on 2026-01-12 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HolaMundo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='age',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Edad'),
        ),
        migrations.AddField(
            model_name='author',
            name='phone_number',
            field=models.CharField(default='', max_length=9, verbose_name='Teléfono'),
        ),
    ]
