# Generated by Django 5.2.8 on 2026-01-12 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HolaMundo', '0003_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='nivel_ingles',
            field=models.CharField(default='', max_length=50, verbose_name='Nivel de inglés'),
        ),
        migrations.AddField(
            model_name='book',
            name='editorial',
            field=models.CharField(default='', max_length=80, verbose_name='Editorial'),
        ),
        migrations.AddField(
            model_name='book',
            name='num_paginas',
            field=models.PositiveSmallIntegerField(default=50, verbose_name='Número de páginas'),
        ),
    ]
